### ISSUE TITLE
Cannot use /me regardless of settings

### ISSUE THREAD

**Issue by mrcoffee1026** [SpaicyGaming/AntiCommandSuggestions#3]
Players all get "&cYou don't have the permission to reload the configuration file!" on every attempt to use /me regardless of setting in file.  I have allowed "me" as a suggestion for the proper whitelist group for rank, but it makes no difference... I have taken the very extreme measure of commenting out every single command in the section that usually affects this... as /me isn't listed in it, I can't remove it from the list to allow it, which I should be able to do:
```
disable-commands-execution:
  blacklist: false
  worldguard-regions:
    - "pl"
  residence-regions: []
  commands:
    exact:
#      - "tp Gasha"
#      - "fly Gasha"
#      - "god Gasha"
    ignore-args:
#      - "pl"
#      - "plugins"
```
In any case, all commands on this list are commented out to prevent their effect, this makes no difference.  I have tried restarting and rejoining with an alternate userID affected by this but nothing has any effect... it is as though the command /me has been hard-coded into the plugin to always be denied by your plugin under all conditions except for users with OP (or possibly permission to *).
